### ISSUE TITLE
default sa requires view permission

### ISSUE THREAD

**Issue by gnunn1** [rromannissen/rhoar-microservices-demo#1]
First thank you for an excellent demo, very easy to setup, works well and highlights some nice features in the various frameworks so kudos.

One minor thing for the documentation, the Spring applications needs view permission in order to access the configmaps, i.e.

``` oc policy add-role-to-user view -z default```

**Comment by rromannissen** [comment]
You are definitely right Gerald! That's something I forgot to add to the documentation. I'm glad you liked the demo, and thanks for the contribution!
